### Ir a la pagina principal
http://localhost:3000

################################ CONSULTAS

### Ruta sin resultados.
GET http://localhost:3000/error
### Ruta sin resultados.
GET http://localhost:3000/invalido



### Mostrar productos por ID
GET http://localhost:3000/productos/66a2ba1e86b2e48ada2b78da
### Mostrar productos por ID
GET http://localhost:3000/productos/66a2af1420f6416fbeeb04bd
### Mostrar productos por ID que no existe
GET http://localhost:3000/productos/14989
### Mostrar productos por ID mal formado
GET http://localhost:3000/productos/1498q1


### Mostrar todos los productos
GET http://localhost:3000/productos/



### Mostrar productos por código
GET http://localhost:3000/productos?codigo=1234
### Mostrar productos por código
GET http://localhost:3000/productos?codigo=1498
### Mostrar productos por código que no existe
GET http://localhost:3000/productos?codigo=1398
### Mostrar productos por código mal formado. Contiene Letras!
GET http://localhost:3000/productos?codigo=1498q1
### Mostrar productos por código mal formado. Mas de 4 cifras!
GET http://localhost:3000/productos?codigo=14989



### Mostrar productos por su nombre o parte de él y su cateroría o parte de ella.
GET http://localhost:3000/productos?nombre=AZuCAR&categoria=Comestible
### Mostrar productos por su nombre o parte de él y su cateroría o parte de ella.
GET http://localhost:3000/productos?nombre=AZUCAR&categoria=Comestible
### Mostrar productos por su nombre o parte de él y su cateroría o parte de ella.
GET http://localhost:3000/productos?nombre=azucar&categoria=COMEStible
### Mostrar productos por su nombre o parte de él y su cateroría o parte de ella.
GET http://localhost:3000/productos?nombre=úcar&categoria=COMEStible
### Mostrar productos por su nombre o parte de él y su cateroría o parte de ella.
GET http://localhost:3000/productos?nombre=CAFE&categoria=INFU
### Mostrar productos por su nombre o parte de él y su cateroría o parte de ella.
GET http://localhost:3000/productos?nombre=JABóN&categoria=lIMP
### Mostrar productos por su nombre o parte de él y su cateroría o parte de ella.
GET http://localhost:3000/productos?nombre=JABON&categoria=PIEza

### Mostrar todos los productos de una categoría
GET http://localhost:3000/productos?categoria=Comestible
### Mostrar todos los productos de una categoría
GET http://localhost:3000/productos?categoria=Limpieza
### Mostrar todos los productos de una secuencia de categoría
GET http://localhost:3000/productos?categoria=lAct
### Mostrar todos los productos de una secuencia de categoría
GET http://localhost:3000/productos?categoria=Infus

### Mostrar productos por su nombre o parte de él.
GET http://localhost:3000/productos?nombre=JABóN
### Mostrar productos por su nombre o parte de él.
GET http://localhost:3000/productos?nombre=Mantequilla
### Mostrar productos por su nombre o parte de él.
GET http://localhost:3000/productos?nombre=equilla
### Mostrar productos por su nombre o parte de él.
GET http://localhost:3000/productos?nombre=caFe

### Mostrar que no se encontraron productos.
GET http://localhost:3000/productos?nombre=caFetería



#############################################################################
############################     OPERACIONES     ############################
#############################################################################

### Agregar un producto

################################ 
### `inx_codigo` es el nombre del indice agregado a la colección como único 
### para que de error si se intenta grabar un código existente!
################################ 

### Agregar un producto con datos validos y sin código para que el sistema lo genere.
### Se la manda tambien un campo extra ("sector") para comprobar que no lo registra!
### Caso 1
POST http://localhost:3000/productos/
content-type: application/json

{
    "nombre": "Trapo de piso 1",
    "precio": 191,
    "categoria": "Limpieza",
    "sector": "sector Limpieza"
}

### Caso 2
POST http://localhost:3000/productos/
content-type: application/json

{
    "nombre": "Trapo de piso 2",
    "precio": 192,
    "categoria": "Limpieza",
    "sector": "sector Limpieza"
}

### Agregar un producto con datos validos y 
### enviando el código para que el sistema lo valide!
POST http://localhost:3000/productos/
content-type: application/json

{
    "codigo": 8808, 
    "nombre": "Trapo de piso 2",
    "precio": 192,
    "categoria": "Limpieza"
}

### Intento de agregar un producto con código repetido par generar 
### un error, controlarlo y avisarlo!
POST http://localhost:3000/productos/
content-type: application/json

{
    "codigo": 9992, 
    "nombre": "Repetido 2",
    "precio": 192,
    "categoria": "Limpieza"
}


### Mostrar nuevo producto ingresado por código.
GET http://localhost:3000/productos/?codigo=9992
### Mostrar nuevo producto ingresado por mombre.
GET http://localhost:3000/productos?nombre=trapo

################################ 
### Modificar un producto
################################ 

### Primero lo consulto 
GET http://localhost:3000/productos/66a70ec478906ce7d4e7104a

### Modificar/Actualizar un producto parcialmente
### Modificar un producto por id. Si devuelve 204 "No Content" 
### se modificó y esta todo bien!
### En este caso se actualiza solo precio. Si llega otro dato, se ignora.
### "nombre": "Trapo de piso eee", está para demostrarlo  !!!
PATCH http://localhost:3000/productos/66a70ec478906ce7d4e7104a
content-type: application/json

{
    "nombre": "Trapo de piso eee",
    "precio": 5688 
}

### En este caso se pasa un body completamente fallido. Debe dar un erro!
### Caso 1
PATCH http://localhost:3000/productos/66a70ec478906ce7d4e7104a
content-type: application/json

{
}

### Caso 2
PATCH http://localhost:3000/productos/66a70ec478906ce7d4e7104a
content-type: application/json

{
    "nombre": "Trapo de piso eee",
    "prexio": 560 
}


################################ 
### Borrar un producto
################################ 

### Primero lo consulto 
GET http://localhost:3000/productos/66a70c7f51fad13b67492809

### Luego borrar un producto por id. Si devuelve 204 "No Content" 
### borró y esta todo bien!
DELETE http://localhost:3000/productos/66a70c7f51fad13b67492809
